config/routes.rb
Rails.application.routes.draw do
  resources :privacy_policy_top_texts
  resources :capsule_learners
  resources :capsule_classes do
    resources :free_study_materials
  end
  resources :learners
  resources :courses do
    resources :fee_structures
  end
  resources :pm_headings
  resources :testimonials
  resources :logo_texts
  resources :menu_items
  resources :corporate_trainer_headings
  resources :corporate_trainers
  resources :pm_logos
  resources :pm_texts
  resources :banner_sections
  resources :positions do
    resources :requirement_categories
  end
  resources :carrer_pages
  resources :policy_hedings do
    resources :policy_sub_hedings
  end
  resources :term_pages
  resources :contact_pages
  resources :teams
  root 'home#index'
  get '/about', to: 'home#about_us', as: 'about'
  get '/contact', to: 'home#contact_us', as: 'contact'
  get '/privacy_policy', to: 'home#privicy_policy', as: 'privacy_policy'  
  get '/terms', to: 'home#t_c', as: 'terms' 
  get 'home/custom'
  post 'home/custom'
  get '/careers', to: 'home#career', as: 'careers'
  get '/admin', to: 'dash#index', as: 'admin'
 
  get '/all_courses', to: 'home#all_courses', as: 'all_courses'
  get '/all_trainers', to: 'home#all_trainers', as: 'all_trainers'
  get '/free_capsule_classes', to: 'home#free_capsule_classes', as: 'free_capsule_classes'
  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :about_pages
  
  #routes
end

app/models/pm_text.rb
class PmText < ActiveRecord::Base
	validates :bottom_text,presence: true, length: {in: 5..400}
end

app/controllers/pm_texts_controller.rb
class PmTextsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pm_text, only: [:show, :edit, :update, :destroy]

  # GET /pm_texts
  # GET /pm_texts.json
  # def index
  #   @pm_texts = PmText.all
  # end

  # GET /pm_texts/1
  # GET /pm_texts/1.json
  def show
  end

  # GET /pm_texts/new
  def new
    @pm_text = PmText.new
  end

  # GET /pm_texts/1/edit
  def edit
  end

  # POST /pm_texts
  # POST /pm_texts.json
  def create
    @pm_text = PmText.new(pm_text_params)

    respond_to do |format|
      if @pm_text.save
        format.html { redirect_to pm_logos_path, notice: 'Pm text was successfully created.' }
        format.json { render :show, status: :created, location: @pm_text }
      else
        format.html { render :new }
        format.json { render json: @pm_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pm_texts/1
  # PATCH/PUT /pm_texts/1.json
  def update
    respond_to do |format|
      if @pm_text.update(pm_text_params)
        format.html { redirect_to pm_logos_path, notice: 'Pm text was successfully updated.' }
        format.json { render :show, status: :ok, location: @pm_text }
      else
        format.html { render :edit }
        format.json { render json: @pm_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pm_texts/1
  # DELETE /pm_texts/1.json
  def destroy
    @pm_text.destroy
    respond_to do |format|
      format.html { redirect_to pm_logos_path, notice: 'Pm text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pm_text
      @pm_text = PmText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pm_text_params
      params.require(:pm_text).permit(:bottom_text)
    end
end

app/helpers/pm_texts_helper.rb
module PmTextsHelper
end

app/views/pm_texts/_form.html.erb
<%= form_for(@pm_text) do |f| %>
  <% if @pm_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pm_text.errors.count, "error") %> prohibited this pm_text from being saved:</h2>

      <ul>
      <% @pm_text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :bottom_text %><br>
    <%= f.text_area :bottom_text ,class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pm_texts/edit.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>Editing Pm Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @pm_text %> |
<%= link_to 'Back', pm_texts_path %>
</div>

app/views/pm_texts/index.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<h1>Listing Pm Texts</h1>

<table>
  <thead>
    <tr>
      <th>Bottom text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pm_texts.each do |pm_text| %>
      <tr>
        <td><%= pm_text.bottom_text %></td>
        <td><%= link_to 'Show', pm_text %></td>
        <td><%= link_to 'Edit', edit_pm_text_path(pm_text) %></td>
        <td><%= link_to 'Destroy', pm_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pm text', new_pm_text_path %>
</div>

app/views/pm_texts/new.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<h1>New Pm Text</h1>

<%= render 'form' %>

<%= link_to 'Back', pm_texts_path %>
</div>

app/views/pm_texts/show.html.erb
<div style="width:88%;margin:0 auto;padding:2%;padding-left:5%;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Bottom text:</strong>
  <%= @pm_text.bottom_text %>
</p>

<%= link_to 'Edit', edit_pm_text_path(@pm_text) %> |
<%= link_to 'Back', pm_logos_path %>
</div>